name: Sync to Hugging Face Hub

on:
  push:
    branches: [main, dev]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push main branch to Hugging Face
        if: github.ref == 'refs/heads/main'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://billmarino:$HF_TOKEN@huggingface.co/spaces/camlsys/compliancecards main

      - name: Push dev branch to Hugging Face
        if: github.ref == 'refs/heads/dev'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://billmarino:$HF_TOKEN@huggingface.co/spaces/camlsys/compliancecards dev